### ISSUE TITLE
Missing Languages in New Polyglot Update.

### ISSUE THREAD

**Issue by AlexisDrain** [Skjalgsm/PolyglotUnity#1]
Polyglot was very recently updated where a new Master sheet was added.
https://docs.google.com/spreadsheets/d/17f0dQawb-s_Fd7DHgmVvJoEGDMH_yoSd8EYigrb0zmM/edit#gid=423963190

In my opinion, this will require changes in this repo:

A) In "LocalizationEditor.cs", the new default gid number should be changed from "296134756" to "423963190". The old number will download "Master_Old" and the new number will download "Master".

B) A few changes in "Langage.cs" are required in my opinion: "Language.cs" is not showing all the new languages in the correct order. This causes issues in "LocalizationImporter.cs". See 1-to-3 below:

1) Selecting the second-to-last language, "Arabic," gives an error because it is listed as number 28. Arabic should be ordered to be number 26, coming right after Hebrew. After doing this minor change, Arabic will become selectable in my tests.

2) Malay and Indonesian have been removed or renamed from the master sheet (?)

3) The last language in the new Master sheet, "Bosnian," is missing and unselectable in the "supported languages." I don't know how to fix this because I don't know what the correct equivalent for "SystemLanguage.Bosnian".

C) (extra) Update the repo to Unity 2017.2

PS. Correct me if I'm wrong about any of the above information. I've only looked at this project today, and I don't know the contribution policy for this plug-in.

**Comment by karmington** [comment]
Hi, Tuomas Karmakallio here, editor of the Master Sheet

I can put the refreshed sheet back in what I renamed to Master_Old to reduce impact of change. 

1) Not sure what the issue is here. Old sheet ordering has not been changed, 2 new languages, Arabic and Bosnian have been added.

2 ) Malaysian and Indonesian columns are not included in Master because they are incomplete.

3) Same as 1?


    On Wednesday, November 29, 2017, 4:05:26 AM GMT+2, Alex Clay <notifications@github.com> wrote:  
 
 
Polyglot was very recently updated where a new Master sheet was added.
https://docs.google.com/spreadsheets/d/17f0dQawb-s_Fd7DHgmVvJoEGDMH_yoSd8EYigrb0zmM/edit#gid=423963190

In my opinion, this will require changes in this repo:

A) Update the repo to Unity 2017.2

B) In "LocalizationEditor.cs", the new default gid number should be changed from "296134756" to "423963190". The old number will download "Master_Old" and the new number will download "Master".

C) A few changes in "Langage.cs" are required in my opinion: "Language.cs" is not showing all the new languages in the correct order. This causes issues in "LocalizationImporter.cs". See 1-to-3 below:
   
   -    
Selecting the second-to-last language, "Arabic," gives an error because it is listed as number 28. Arabic should be ordered to be number 26, coming right after Hebrew. After doing this minor change, Arabic will become selectable in my tests.

   -    
Malay and Indonesian have been removed or renamed from the master sheet (?)

   -    
The last language in the new Master sheet, "Bosnian," is missing and unselectable in the "supported languages." I don't know how to fix this because I don't know what the correct equivalent for "SystemLanguage.Bosnian".


PS. Correct me if I'm wrong about any of the above information. I've only looked at this project today, and I don't know the contribution policy for this plug-in.

**Comment by skjalgsm** [comment]
Nice to be notified of these issues, thanks!
Updating the gid is a minor fix, but it would be nice if it stayed the
same. As for the other issues, I’ll take a look at them and see what I
figure out. I also have some other changes in the works.

**Comment by karmington** [comment]
I'll just copy over to the original, no problem.
    On Wednesday, November 29, 2017, 4:09:48 PM GMT+2, Skjalg Sturlasson Mæhre <notifications@github.com> wrote:  
 
 Nice to be notified of these issues, thanks!
Updating the gid is a minor fix, but it would be nice if it stayed the
same. As for the other issues, I’ll take a look at them and see what I
figure out. I also have some other changes in the works.

**Comment by skjalgsm** [comment]
Nice. I've now updated the project with the new language list.

**Comment by AlexisDrain** [comment]
Thank you so much for the timely update!

However, I downloaded a fresh master branch of this repo and I am afraid to inform you that I cannot build project anymore! It gives me an error saying it's missing a TMPro. This did not happen yesterday before the current commit. I think the flag **#if TMP_PRESENT** isn't working anymore

I'm using Unity 2017.2.0f3 Personal.

![sprite-0001](https://user-images.githubusercontent.com/32722574/33392434-0cf5a936-d50a-11e7-9d09-ca4d8314399f.png)

**Comment by AlexisDrain** [comment]
Sorry for the last comment! I solved my issue by consulting the readme file. I had to remove the **TMP** tag from **"Player Settings > Other Settings > Scripting Define Symbols"** which is currently enabled by default in the **PolyglotUnity** project.

Everything is working correctly now. Thanks again!

**Comment by skjalgsm** [comment]
Oops. I didnt mean to commit the changes to ProjectSettings. Nice that you
fixed it.
