### ISSUE TITLE
Adding Arabic support in Unity Projects

### ISSUE THREAD

**Issue by AlexisDrain** [Skjalgsm/PolyglotUnity#2]
I have translated the Polyglot master sheet to Arabic, but there is a severe issue that needs to be addressed in order to use this language in Unity.

Arabic is a cursive language where the letters in every word are connected to each other using alternative font characters. Unity, however, doesn't recognize that use-case and the Arabic words are split up and illegible. This can be fixed using a free store asset called "Arabic Support" also licensed under MIT like "PolyglotUnity".

It is found here:
https://www.assetstore.unity3d.com/en/#!/content/2674
https://github.com/Konash/arabic-support-unity

In order to fix the Arabic language for "PolyglotUnity", here are my suggested changes to this repo:

A) Put the file "Arabic Support > ArabicSupport.dll" into this repo.

B) In "PolyglotUnity > LocalizedText.cs > SetText()", add an if condition for Arabic:

```
protected override void SetText(Text text, string value) {
    if (text == null) {
        Debug.LogWarning("Missing text component for " + this, this);
        return;
    }
    if (Localization.Instance.SelectedLanguage == Language.Arabic) {
	text.text = ArabicFixer.Fix(value, true, true);
    } else {
        text.text = value;
    }
}
```
Here is the result (Before & after):
![sprite-0007](https://user-images.githubusercontent.com/32722574/33355106-0bcc56d0-d484-11e7-9bca-9adef34cff42.png)

Of course, I believe this should be done with the approval of the author of "Arabic Support" @Konash and the maintainers of this repo.

**Comment by skjalgsm** [comment]
Thank you for this in depth solution to a common problem for arabic. I really appreciate this.

I was not comfortable just adding the ArabicSupport.cs file from that repo to this repo, but I have added it as an option to use it if you specify ARABSUPPORT_ENABLED in Player Settings -> Scripting Define Symbols in v1.2. 

This release will use the ArabFixer.Fix method when grabbing the text from the imported localization. I did not alter LocalizedText as you suggested, but rather higher up in the system so that LocalizedTextMesh and LocalizedTextMeshProUGUI would also be affected by the change.

Hope you are happy with the changes I made. Please repoen this if you have any issues.

**Comment by AlexisDrain** [comment]
Really, really appreciate all the new support for Arabic!

I like making the ShowTashkeel and HinduNumbers public. And the hover message on them to warn the user to enable ARABSUPPORT_ENABLED flag.

Maybe one minor precaution that I would suggest is that I feel the plugin should log a warning/error in the console if the user switched to Arabic and ARABSUPPORT_ENABLED wasn't enabled. After all, not enabling ARABSUPPORT_ENABLED makes the language completely illegible to the user. [I wouldn't want this to happen.](https://nopenotarabic.tumblr.com/image/127857870018)

**Comment by Konash** [comment]
Glad the plugin is being useful for many <3

**Comment by skjalgsm** [comment]
Nice suggestion. I’ll look at adding something like this.
