### ISSUE TITLE
How to add a new language?

### ISSUE THREAD

**Issue by carlosvVk** [Skjalgsm/PolyglotUnity#26]
Hi!

I've been using polyglot for a while, and I LOVE this tool, it's crazy useful. Now, I want to add a new language that it's not included in the default languages (Galician, from Spain), but I don't know how. I have added it to the enum "Languages" but it does weird things.

Is there an easy way?

Thanks!
Carlos

**Comment by skjalgsm** [comment]
Did you add the enum at the end of the other langauges? The list of languages in the enum must correspond with the list of languages in the input file that is being parsed. So if you add Galacian to the end, you also need to add a column to the google sheet. Otherwise you will get an index out of bounds exception as the importer will try to read the input file but theres a mismatch of how many columns the input file has versus how many languages there are in the enum.
![image](https://user-images.githubusercontent.com/568589/97604825-31a9ad80-1a0e-11eb-9e88-d50934f37f79.png)

**Comment by carlosvVk** [comment]
That was it, I had only 6 languages but wanted to put it in the third position. Adding it at 7th solved it. 

Thanks for your support!
