### ISSUE TITLE
Better documentation on integration for Custom Sheet

### ISSUE THREAD

**Issue by henriqueranj** [Skjalgsm/PolyglotUnity#4]
Hello, I am really enjoying this plugin for localisation! Thank you very much for it!

However, I struggled to get it up and running with a custom localisation file. It would be great to have better documentation about it, as I had to debug the code to understand how the formats and requirements for the localisation file are.

As I wish for new developers to have an easier time when integrating this tool, I would suggest to:
1. Explain the required format for the localisation spreadsheet: localisation strings are only parsed after a row that start with "Polyglot"/"PolyMaster"/"BEGIN".
2. Explain the the parsing ends when it meets a row that starts with "END".
3. Explain that the custom spreadsheet needs to follow the same number and order of localised languages columns as the master sheet (plugin code relies on Languages enum's int numbers to fetch the language).
4. Provide a template of a localisation spreadsheet that new developers can start from.
5. Explain that the custom sheet needs to be a publicly available Google Spreadsheet so it can be downloaded via the Editor tool.

**Comment by skjalgsm** [comment]
This is really great feedback. Thank you.

I will make this happen very soon. We just had some troubles with this ourselves internally just yesterday someone on the team noticed that half of our localization strings were missing from the game because an END keyword had been inserted in the middle with translations, so its an undocumented feature for sure :)

**Comment by skjalgsm** [comment]
Closed as I address this in the recent release
